#!/usr/bin/env python3

import os
import os.path as osp
import subprocess
import sys

dir = osp.dirname(osp.abspath(sys.argv[0]))

image = os.environ['SINGULARITY_CONTAINER']
image_link = osp.join(build, 'image')
if not osp.exists(image_link):
    os.symlink(image,
               image_link)

src = osp.join(dir, 'src')
if not osp.exists(src)
    os.mkdir(src)
    subprocess.check_call(['vcs', 'import'], 
                            stdin=open(osp.join(src, 'components.yaml')),
                            cwd=src)
bin =osp.join(dir, 'bin')
if not osp.exists(bin):
    os.mkdir(bin)
    os.symlink(osp.join(src, 'brainvisa-cmake', 'bin', 'bv2'),
               osp.join(bin, 'bv2'))
 